[project]
name = "ppois4"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.12.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
]
